# Generated by Django 3.2 on 2021-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('approuve', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
